#
# Makefile for the Linux IrDA IrCOMM protocol layer.
#

subdir-ccflags-y += -I$(src)/../../include

obj-m += ircomm.o ircomm-tty.o

ircomm-y := ircomm_core.o ircomm_event.o ircomm_lmp.o ircomm_ttp.o
ircomm-tty-y := ircomm_tty.o ircomm_tty_attach.o ircomm_tty_ioctl.o ircomm_param.o
